# Generated by Django 5.0.2 on 2024-02-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flour',
            old_name='image',
            new_name='flour_image',
        ),
    ]
