# Generated by Django 5.0.2 on 2024-02-27 13:24

import utils.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flour', '0002_rename_image_flour_flour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flour',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flour',
            name='flour_image',
            field=models.ImageField(upload_to=utils.image_path.upload_images, verbose_name='Картинка'),
        ),
    ]
