# Generated by Django 5.0.2 on 2024-02-28 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flour', '0003_flour_description_alter_flour_flour_image'),
        ('tort', '0004_tort_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Каличество')),
                ('flour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flour', to='flour.flour')),
                ('tort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tort', to='tort.tort')),
            ],
            options={
                'verbose_name': 'Избранный',
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
