# Generated by Django 5.0.2 on 2024-03-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('flour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='flour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flour.flour', verbose_name='Мучное'),
        ),
    ]
