# Generated by Django 5.0.2 on 2024-03-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_carditem_flour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carditem',
            name='flour',
        ),
    ]
