# Generated by Django 5.0.2 on 2024-02-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_flour_alter_cart_tort'),
        ('flour', '0003_flour_description_alter_flour_flour_image'),
        ('tort', '0004_tort_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='flour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flour', to='flour.flour'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tort', to='tort.tort'),
        ),
    ]
