# Generated by Django 5.0.2 on 2024-03-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_carditem_flour'),
        ('flour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardItemFlour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flour_items', to='cart.card', verbose_name='Карзина')),
                ('flour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flour.flour', verbose_name='Мучное')),
            ],
        ),
    ]
