# Generated by Django 5.0.2 on 2024-02-26 14:00

import utils.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tort',
            options={'verbose_name': 'Торт', 'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterField(
            model_name='tort',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.image_path.upload_products, verbose_name='Картинка'),
        ),
    ]
