# Generated by Django 5.0.2 on 2024-02-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tort', '0002_alter_tort_options_alter_tort_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tort',
            old_name='image',
            new_name='tort_image',
        ),
    ]
